name: mezobeli-scrap

on:
    schedule:
        - cron: "* */72 * * *"
jobs:
    scrap:
        runs-on: ubuntu-latest
        env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
        steps:
            - uses: actions/checkout@v4
            - name: Use Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
            - name: Install Dependencies
              env:
                  MONGO_URI: ${{ secrets.MONGO_URI }}
              run: npm ci
            - run: npm run scrap
